name = "mascarpone"
version = "1.1.0"
target = "erlang"
description = "CLI tool for scaffolding Tiramisu game projects"
licences = ["MIT"]
repository = { type = "github", user = "renatillas", repo = "mascarpone" }

[dependencies]
gleam_stdlib = ">= 0.64.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
shore = ">= 1.3.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
snag = ">= 1.1.0 and < 2.0.0"
tom = ">= 2.0.0 and < 3.0.0"
operating_system = ">= 1.0.1 and < 2.0.0"
shellout = ">= 1.7.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
